# Copyright 2023 Aineko Authors
# SPDX-License-Identifier: Apache-2.0
site_name: Aineko
site_url: https://docs.aineko.dev/
repo_name: aineko-dev/aineko
repo_url: https://github.com/aineko-dev/aineko
edit_uri: edit/develop/docs/
theme:
  name: material
  palette:
    scheme: aineko
  icon:
    repo: fontawesome/brands/github
  favicon: assets/favicon_green.svg
  logo: assets/favicon_white.svg
  font:
    size: 20
  features:
    - content.action.edit
    - content.code.copy
    - navigation.tabs
    - navigation.path
    - navigation.footer
    - navigation.indexes
    - navigation.tracking
    - navigation.top
    - toc.follow
    - content.code.annotate
extra_css:
  - stylesheets/extra.css
extra:
  generator: false
  version:
    provider: mike
  analytics:
    provider: google
    property: G-395240980
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/aineko-dev/aineko
    - icon: fontawesome/brands/chrome
      link: https://aineko.dev
copyright: Copyright &copy; 2023 Convex Research

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - def_list
  - attr_list
  - md_in_html
  - mkdocs-click
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  - glightbox
  - search
  - mike:
      alias_type: copy
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            extension:
              - griffe_typingdoc
            show_root_heading: true

nav:
  - Aineko Framework:
      - 'index.md'
      - Get Started:
          - 'start/quickstart.md'
      - Developer Guide:
          - 'developer_guide/concepts.md'
          - 'developer_guide/aineko_project.md'
          - 'developer_guide/pipeline_configuration.md'
          - 'developer_guide/node_implementation.md'
          - 'developer_guide/cli.md'
          - 'developer_guide/config_kafka.md'
      - Extras:
          - extras/intro.md
          - extras/fastapi.md
      - API Documentation:
          - 'api_reference/abstract_node.md'
          - 'api_reference/dataset_consumer.md'
          - 'api_reference/dataset_producer.md'
          - 'api_reference/config.md'
          - 'api_reference/config_loader.md'
          - 'api_reference/runner.md'
      - Example Pipelines:
          - examples/aineko_dream.md
      - Community:
          - community/index.md

  - Aineko Cloud: 'https://cloud-docs.aineko.dev'
