# Copyright 2023 Aineko Authors
# SPDX-License-Identifier: Apache-2.0
version: 2.1

parameters:
  python_version:
    description: Version to python to use
    type: string
    default: "3.10"

workflows:
  continuous-integration:
    jobs:
      - python-checks:
          filters:
            branches:
              ignore: develop
          prj_dir: aineko
          python_version: << pipeline.parameters.python_version >>
          markers: "not integration"
      - integration-tests:
          prj_dir: aineko
          python_version: << pipeline.parameters.python_version >>
          markers: integration

  publish-docs:
    jobs:
      - build-and-push-docs:
          name: publish dev docs
          filters:
            branches:
              only: develop
      - build-and-push-docs:
          name: publish versioned docs
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /\d+\.\d+\.\d+$/
          version: << pipeline.git.tag >>
          tag: true

jobs:
  integration-tests:
    parameters:
      python_version:
        type: string
        default: "3.10"
        description: Version of python to use
      prj_dir:
        type: string
        default: $CIRCLE_PROJECT_REPONAME
        description: Directory of codebase to execute checks
      test_dir:
        type: string
        default: tests
        description: Test directory
      markers:
        type: string
        default: integration
        description: Markers to run pytest for

    docker:
      - image: cimg/python:<< parameters.python_version >>
      - image: confluentinc/cp-zookeeper:7.3.0
        name: zookeeper
        environment:
          ZOOKEEPER_CLIENT_PORT: 2181
          ZOOKEEPER_TICK_TIME: 2000
      - image: confluentinc/cp-kafka:7.3.0
        environment:
          KAFKA_BROKER_ID: 1
          KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
          KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
          KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
          KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
          KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
          KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

    steps:
      - checkout
      - run: poetry install --with test --no-interaction --quiet
      - run: >
          poetry run pytest << parameters.test_dir >>
          -m "<< parameters.markers >>"

  python-checks:
    parameters:
      python_version:
        type: string
        default: "3.10"
        description: Version of python to use
      prj_dir:
        type: string
        default: $CIRCLE_PROJECT_REPONAME
        description: Directory of codebase to execute checks
      test_dir:
        type: string
        default: tests
        description: Test directory
      markers:
        type: string
        default: ""
        description: Markers to run pytest for

    docker:
      - image: cimg/python:<< parameters.python_version >>

    steps:
      - checkout
      - run: poetry install --with dev,test --no-interaction --quiet
      - run: poetry run isort << parameters.prj_dir >>
      - run: poetry run black << parameters.prj_dir >> --check
      - run: poetry run pydocstyle << parameters.prj_dir >>
      - run: poetry run pylint << parameters.prj_dir >>
      - run: poetry run yamllint -c yamllint.yaml << parameters.prj_dir >>
      - run: |
          poetry run pre-commit install
          poetry run pre-commit run --all
      - run: >
          poetry run pytest
          --cov=<< parameters.prj_dir >> << parameters.test_dir >>
          -m "<< parameters.markers >>"
      - run:
          name: mypy
          command: |
            poetry run mypy --install-types \
            --non-interactive << parameters.prj_dir >>
            poetry run mypy << parameters.prj_dir >>

  build-and-push-docs:
    parameters:
      docs_branch:
        type: string
        default: docs-site
        description: Branch to publish docs site files to
      version:
        type: string
        default: dev
        description: Version of docs to publish
      tag:
        type: boolean
        default: false
        description: If version is a tag
    docker:
      - image: cimg/python:<< pipeline.parameters.python_version >>
    steps:
      - add_ssh_keys:
          fingerprints:
            - "18:33:31:05:d5:48:ad:0c:78:8d:23:5c:13:d1:04:ce"
      - checkout
      - run: poetry install --with docs --no-interaction --quiet
      - run: git config user.name aineko-ci
      - run: git config user.email engineering-admins@convexlabs.xyz
      - run: |
          if [ "<< parameters.tag >>" = "true" ]; then
            version=$(echo "<< parameters.version >>" | cut -d'.' -f1,2)
            poetry run mike deploy $version -b << parameters.docs_branch >> --push
          else
            poetry run mike deploy << parameters.version >> -b << parameters.docs_branch >> --push
          fi
